# Azure pipeline definition for the packaging of the solution (continuous delivery)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr: none

variables:
# library variable groups
- group: 'build-tools'
# environment variables
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'Devpro.AspNetCoreTestingSample.sln'
# specific variables
- name: 'dotnet.sdk.version'
  value: '3.1.100'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: $(dotnet.sdk.version)
- task: DotNetCoreCLI@2
  displayName: 'Publish the ASP.NET Web App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/**/*App.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/webapp'
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: 'Save artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
